import Head from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import reqObj from "../utils/requests";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Zulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <Results results={props.results} />
    </>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(
    `https://api.themoviedb.org/3${
      reqObj[genre]?.url || reqObj.fetchTrending.url
    }`
  )
    .then((res) => res.json())
    .catch((err) => console.log(err));

  return {
    props: {
      results: request.results,
    },
  };
}
